CREATE TRIGGER trg_DeleteOrderAndDetails
ON Orders
INSTEAD OF DELETE
AS
BEGIN
 
    DELETE FROM OrderDetails
    WHERE OrderID IN (SELECT OrderID FROM DELETED)


    DELETE FROM Orders
    WHERE OrderID IN (SELECT OrderID FROM DELETED)

END 
